### PR TITLE
feature - Add Databricks connection

### LINKED ISSUE #78: Databricks connection type
Is there a way to use this provider with the databricks connection on a project? looking through the code looks like only snowflake and bigquery is supported? https://github.com/GtheSheep/terraform-provider-dbt-cloud/blob/86c89283157915277916ae315beb11fe5ea9db7a/pkg/resources/connection.go#L14

### PR DESCRIPTION
**Pull request by GtheSheep**
Closes #78

### CODE REVIEW

**Comment by matmiad** [comment]
> Hia @GtheSheep, thanks for all your efforts on this provider. How far away do you think this PR is? I was planning to migrate our dbt-cloud set up into terraform and this PR would be necessary to make that complete. Let me know if you need help with any testing! Thanks!

Echoing the above. Your work is much appreciated!

**Comment by GtheSheep** [comment]
Hey both! Thanks for your interest, sorry for being a little bit absent, start of the new year and all that! But yeah I did forget about this one a little bit, I'll try and review it this week for code completeness, but as I don't have a Databricks account/ have never worked with it I'd really appreciate any help and feedback you could provide testing it if I make a release?! Thanks! 😸

**Comment by troyel** [comment]
@GtheSheep : Very happy to test! 👍

**Comment by matmiad** [comment]
@GtheSheep same here, happy to test and help out. Thanks!

**Comment by GtheSheep** [comment]
@troyel @matmiad thanks both!

**Pull request merged**
